# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "gdata_spreadsheet"
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Tom"]
  s.date = "2013-02-20"
  s.description = ""
  s.email = "tom@trike.com.au"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "gdata_spreadsheet.gemspec",
    "lib/gdata_spreadsheet.rb",
    "lib/google/base.rb",
    "lib/google/config.rb",
    "lib/google/log.rb",
    "lib/google/spreadsheet.rb",
    "spec/google/base_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/tricycle/gdata_spreadsheet"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Simple wrapper to access a google spreadsheet using the GData gem"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<gdata>, [">= 0"])
    else
      s.add_dependency(%q<gdata>, [">= 0"])
    end
  else
    s.add_dependency(%q<gdata>, [">= 0"])
  end
end

